// <auto-generated />
using FS.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FS.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260628225130_AnimalAnnouncementDeleteTypeMigration")]
    partial class AnimalAnnouncementDeleteTypeMigration
    {
    }
}
