// <auto-generated />
using System;
using FS.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace FS.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FS.Core.AnimalAnnouncementBC.AnimalAnnouncement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("House")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<int>("PetType")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("AnimalAnnouncements", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FS.Core.ImageDomain.Entities.FSImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AnimalAnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<string>("BucketURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(512)");

                    b.Property<string>("FullImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("S3Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalAnnouncementId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("FS.Core.NotificationDomain.Entities.NotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("Channel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserDeviceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserDeviceId");

                    b.ToTable("NotificationDeliveries", (string)null);
                });

            modelBuilder.Entity("FS.Core.NotificationDomain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("Channels")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("FS.Core.OutboxDomain.Entities.OutboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutboxEvents", (string)null);
                });

            modelBuilder.Entity("FS.Core.ReadDomain.SimilarAnnouncements", b =>
                {
                    b.Property<Guid>("StreetPetAnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MissingAnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StreetPetAnnouncementId", "MissingAnnouncementId");

                    b.HasIndex("MissingAnnouncementId");

                    b.ToTable("SimilarAnnouncements", (string)null);
                });

            modelBuilder.Entity("FS.Core.SearchDomain.SearchRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(512)");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<int>("SearchRequestStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("SearchRequests", (string)null);
                });

            modelBuilder.Entity("FS.Core.UserDomain.Entities.UserDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices", (string)null);
                });

            modelBuilder.Entity("FS.Core.UserDomain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AvatarImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Point>("LastCoordinates")
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AvatarImageId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SearchResults", b =>
                {
                    b.Property<Guid>("AnimalAnnouncementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SearchRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("AnimalAnnouncementId", "SearchRequestId");

                    b.HasIndex("SearchRequestId");

                    b.ToTable("SearchResults", (string)null);
                });

            modelBuilder.Entity("FS.Core.AnimalAnnouncementBC.PetAnnouncement", b =>
                {
                    b.HasBaseType("FS.Core.AnimalAnnouncementBC.AnimalAnnouncement");

                    b.Property<string>("Breed")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");
                });

            modelBuilder.Entity("FS.Core.AnimalAnnouncementBC.StreetPetAnnouncement", b =>
                {
                    b.HasBaseType("FS.Core.AnimalAnnouncementBC.AnimalAnnouncement");

                    b.Property<string>("PlaceDescription")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("FS.Core.AnimalAnnouncementBC.FindAnnouncement", b =>
                {
                    b.HasBaseType("FS.Core.AnimalAnnouncementBC.PetAnnouncement");

                    b.Property<int>("DeleteReason")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("FS.Core.AnimalAnnouncementBC.MissingAnnouncement", b =>
                {
                    b.HasBaseType("FS.Core.AnimalAnnouncementBC.PetAnnouncement");

                    b.Property<int>("DeleteReason")
                        .HasColumnType("integer");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("AnimalAnnouncements", null, t =>
                        {
                            t.Property("DeleteReason")
                                .HasColumnName("MissingAnnouncement_DeleteReason");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("FS.Core.AnimalAnnouncementBC.AnimalAnnouncement", b =>
                {
                    b.HasOne("FS.Core.UserDomain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FS.Core.ImageDomain.Entities.FSImage", b =>
                {
                    b.HasOne("FS.Core.AnimalAnnouncementBC.AnimalAnnouncement", null)
                        .WithMany("Images")
                        .HasForeignKey("AnimalAnnouncementId");
                });

            modelBuilder.Entity("FS.Core.NotificationDomain.Entities.NotificationDelivery", b =>
                {
                    b.HasOne("FS.Core.NotificationDomain.Notification", null)
                        .WithMany("NotificationDeliveries")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FS.Core.UserDomain.Entities.UserDevice", null)
                        .WithMany()
                        .HasForeignKey("UserDeviceId");
                });

            modelBuilder.Entity("FS.Core.ReadDomain.SimilarAnnouncements", b =>
                {
                    b.HasOne("FS.Core.AnimalAnnouncementBC.MissingAnnouncement", null)
                        .WithMany()
                        .HasForeignKey("MissingAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FS.Core.AnimalAnnouncementBC.StreetPetAnnouncement", null)
                        .WithMany()
                        .HasForeignKey("StreetPetAnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FS.Core.SearchDomain.SearchRequest", b =>
                {
                    b.HasOne("FS.Core.ImageDomain.Entities.FSImage", "Image")
                        .WithOne()
                        .HasForeignKey("FS.Core.SearchDomain.SearchRequest", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("FS.Core.UserDomain.Entities.UserDevice", b =>
                {
                    b.HasOne("FS.Core.UserDomain.User", null)
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FS.Core.UserDomain.User", b =>
                {
                    b.HasOne("FS.Core.ImageDomain.Entities.FSImage", null)
                        .WithOne()
                        .HasForeignKey("FS.Core.UserDomain.User", "AvatarImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsMany("FS.Core.UserDomain.Entities.UserContact", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserContacts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("FS.Core.UserDomain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("FS.Core.UserDomain.ValueObjects.FullName", "FullName", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("FirstName");

                            b1.Property<string>("Patronymic")
                                .HasColumnType("text")
                                .HasColumnName("Patronymic");

                            b1.Property<string>("SecondName")
                                .HasColumnType("text")
                                .HasColumnName("SecondName");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Contacts");

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("FullName")
                        .IsRequired();
                });

            modelBuilder.Entity("SearchResults", b =>
                {
                    b.HasOne("FS.Core.AnimalAnnouncementBC.AnimalAnnouncement", null)
                        .WithMany()
                        .HasForeignKey("AnimalAnnouncementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FS.Core.SearchDomain.SearchRequest", null)
                        .WithMany()
                        .HasForeignKey("SearchRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FS.Core.AnimalAnnouncementBC.AnimalAnnouncement", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("FS.Core.NotificationDomain.Notification", b =>
                {
                    b.Navigation("NotificationDeliveries");
                });

            modelBuilder.Entity("FS.Core.UserDomain.User", b =>
                {
                    b.Navigation("UserDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
