{
 "title": "Logs dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {}
   },
   {
    "name": "app",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Errors over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (\r\n  count_over_time(\r\n    {app=\"$app\", environment=\"$environment\"}\r\n    | json\r\n    | label_format level=\"{{.level}}\"\r\n    | level =~ \"error|fatal\"\r\n    [5m]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Logs by level",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (\r\n  count_over_time(\r\n    {app=\"$app\", environment=\"$environment\"}\r\n    | json\r\n    | level != \"\"\r\n    [5m]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Recent error logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"$app\", environment=\"$environment\"}\r\n| json\r\n| level =~ \"error|fatal\""
    }
   ]
  }
 ]
}