services:
  fs-api:
    image: olzar/fs-api:0.28
    environment:
      ConnectionStrings__DefaultConnection: "Server=fs-pg;Port=5432;Database=FootSteps;User Id=postgres;Password=12345"
      JwtOptions__SecretKey: "IBau9AzKLsV1zlxPwCMxrOuboFHIpD7G"
      S3StorageConfiguration__AccessKey: "YCAJELa6CRTzJXiPuTSfwYICH"
      S3StorageConfiguration__SecretKey: "YCNYi4w2vO-ALGsMEFHoFa6D_gyxZ2IGXGIEGW02"
      YandexApiOptions__ApiKey: "6b204097-db10-4e17-b602-aac7dc99c1e6"
      RabbitMqOptions__Uri: "amqp://guest:guest@rabbitmq:5672/"
      OltpOptions__Uri: "http://tempo:4317"
      Serilog__WriteTo__1__Args__uri: "http://loki:3100"
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - fs-pg
      - rabbitmq
      - grafana
      - tempo
      - loki
    networks:
      - fs-net
  fs-pg:
    image: olzar/postgres-geo-vec
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "FootSteps"
      POSTGRES_PASSWORD: "12345"
    networks:
      - fs-net
    volumes:
      - fs-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d FootSteps" ]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5434:5432"
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fs-net
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./Grafana/dashboards:/etc/grafana/dashboards
      - ./Grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
      - tempo
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - fs-net
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    volumes:
      - ./Loki/config:/etc/loki/config
      - ./Loki/data:/loki
    command: [ "-config.file=/etc/loki/config/loki-config.yaml" ]
    networks:
      - fs-net
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo/config/tempo-config.yaml" ]
    volumes:
      - ./Tempo/config:/etc/tempo/config
      - ./Tempo/data:/var/tempo
    networks:
      - fs-net
networks:
  fs-net:
    driver: bridge